# Generated by Django 6.0.2 on 2026-02-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Manager', 'MANAGER'), ('Developer', 'Developer')], default='Developer', max_length=20),
        ),
    ]
